spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

sms:
  key: OCBgHh0BBvxB37lQjfpWUgar
  secret: b(FBolUMZXa3nKLC9dyB0hNnk.V-NYCImYavrTSh